apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: nelson211/mi-api:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: Mongo_uri
              value: "mongodb+srv://oa3973392:sRNos5WRutXoYt2I@cluster0.vlf3f.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: SECRET_KEY
              value: "abcdefghijklmnopqrstuvwxyz1234567890$!@#=))((***))"
            - name: Email_User
              value: "asistentedetareas623@gmail.com"
            - name: Email_Pass
              value: "sxtabgrstoedkijq"

